version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  redis:
    image: redis:7.2
    container_name: redis
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "6379:6379"
